name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Container Registry
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build --tag gcr.io/predictive-guru-425117-r4/spring-boot-app:$GITHUB_SHA .

      - name: Push Docker image
        run: docker push gcr.io/predictive-guru-425117-r4/spring-boot-app:$GITHUB_SHA

      - name: Set up kubectl
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: predictive-guru-425117-r4
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get GKE credentials
        run: |
          gcloud components install kubectl
          gcloud container clusters get-credentials primary-cluster --region us-central1

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl set image deployment/spring-boot-app spring-boot-app=gcr.io/predictive-guru-425117-r4/spring-boot-app:$GITHUB_SHA
